# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='habilidad_evaluada',
            field=models.TextField(
                blank=True,
                verbose_name='Habilidad Evaluada',
                help_text='Descripción de la competencia o habilidad específica que evalúa esta pregunta'
            ),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='explicacion_opciones_incorrectas',
            field=models.JSONField(
                default=dict,
                verbose_name='Explicación de Opciones Incorrectas',
                help_text='Explicación detallada de por qué cada opción incorrecta no es válida'
            ),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='estrategias_resolucion',
            field=models.TextField(
                blank=True,
                verbose_name='Estrategias de Resolución',
                help_text='Técnicas y estrategias para abordar este tipo de preguntas'
            ),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='errores_comunes',
            field=models.TextField(
                blank=True,
                verbose_name='Errores Comunes',
                help_text='Errores frecuentes que cometen los estudiantes en este tipo de pregunta'
            ),
        ),
    ]