# Generated by Django 4.2.7 on 2025-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_pregunta_retroalimentacion_estructurada"),
    ]

    operations = [
        migrations.AddField(
            model_name="pregunta",
            name="imagen",
            field=models.ImageField(
                blank=True,
                help_text="Imagen opcional para análisis, gráficos, diagramas, mapas, etc.",
                null=True,
                upload_to="preguntas/imagenes/%Y/%m/",
                verbose_name="Imagen de Contexto",
            ),
        ),
    ]
