# Generated by Django 4.2.7 on 2025-08-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_imagen_to_pregunta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("estudiante", "Estudiante"),
                    ("docente", "Docente"),
                    ("admin", "Administrador"),
                ],
                default="estudiante",
                max_length=10,
                verbose_name="Rol",
            ),
        ),
    ]
