# Generated by Django 4.2.7 on 2025-08-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_usuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="configuracion",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Configuración"
            ),
        ),
    ]
