# Generated by Django 4.2.7 on 2025-08-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_usuario_configuracion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pregunta",
            name="retroalimentacion_estructurada",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Retroalimentación Estructurada"
            ),
        ),
    ]
