# Generated by Django 4.2.7 on 2025-08-03 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0005_alter_usuario_configuracion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaSimulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "cantidad_preguntas",
                    models.IntegerField(
                        default=10, verbose_name="Cantidad de Preguntas"
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_simulacion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Docente",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_simulacion",
                        to="core.materia",
                        verbose_name="Materia",
                    ),
                ),
                (
                    "preguntas_especificas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="plantillas_simulacion",
                        to="core.pregunta",
                        verbose_name="Preguntas Específicas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Simulación",
                "verbose_name_plural": "Plantillas de Simulación",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
