# Generated by Django 4.2.7 on 2025-08-03 20:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_usuario_configuracion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("simulacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreguntaSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "respuesta_estudiante",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="Respuesta del Estudiante",
                    ),
                ),
                (
                    "es_correcta",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="¿Es Correcta?"
                    ),
                ),
                (
                    "tiempo_respuesta",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tiempo de Respuesta (segundos)",
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(default=0, verbose_name="Orden de la Pregunta"),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones_pregunta",
                        to="core.pregunta",
                        verbose_name="Pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta de Sesión",
                "verbose_name_plural": "Preguntas de Sesión",
                "db_table": "preguntas_sesion",
                "ordering": ["orden"],
            },
        ),
        migrations.AlterField(
            model_name="plantillasimulacion",
            name="cantidad_preguntas",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Cantidad de Preguntas",
            ),
        ),
        migrations.AlterField(
            model_name="plantillasimulacion",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Modificación"
            ),
        ),
        migrations.AlterField(
            model_name="plantillasimulacion",
            name="preguntas_especificas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selecciona preguntas específicas para esta simulación. Si no se seleccionan, se usarán preguntas aleatorias.",
                to="core.pregunta",
                verbose_name="Preguntas Específicas",
            ),
        ),
        migrations.AlterField(
            model_name="plantillasimulacion",
            name="titulo",
            field=models.CharField(
                max_length=200, verbose_name="Título de la Plantilla"
            ),
        ),
        migrations.AlterModelTable(
            name="plantillasimulacion",
            table="plantillas_simulacion",
        ),
        migrations.CreateModel(
            name="SesionSimulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Finalización"
                    ),
                ),
                (
                    "completada",
                    models.BooleanField(default=False, verbose_name="Completada"),
                ),
                (
                    "puntuacion",
                    models.IntegerField(default=0, verbose_name="Puntuación"),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones_simulacion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones_simulacion",
                        to="core.materia",
                        verbose_name="Materia",
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sesiones",
                        to="simulacion.plantillasimulacion",
                        verbose_name="Plantilla de Simulación",
                    ),
                ),
                (
                    "preguntas",
                    models.ManyToManyField(
                        through="simulacion.PreguntaSesion",
                        to="core.pregunta",
                        verbose_name="Preguntas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Simulación",
                "verbose_name_plural": "Sesiones de Simulación",
                "db_table": "sesiones_simulacion",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.AddField(
            model_name="preguntasesion",
            name="sesion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas_sesion",
                to="simulacion.sesionsimulacion",
                verbose_name="Sesión",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="preguntasesion",
            unique_together={("sesion", "pregunta")},
        ),
    ]
