# Generated by Django 4.2.7 on 2025-08-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulacion", "0002_preguntasesion_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sesionsimulacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completada", False)),
                fields=("estudiante", "materia"),
                name="unique_active_session_per_student_subject",
            ),
        ),
    ]
